### ISSUE TITLE
TypeError: _this.addWatchFile is not a function on rollup < 1

### ISSUE THREAD

**Issue by jnields** [egoist/rollup-plugin-postcss#161]
This happens with rollup < 1 - would it be appropriate to add rollup@1 as a peer dependency?

**Comment by wardpeet** [comment]
Thank you for opening the issue, we haven't got any more issues around this problem for a while. We moved to rollup version 2 as a required version, so I'm closing this bug because it doesn't seem relevant anymore.

If this is not the case, please re-open or create a new ticket with new information. Thank you!
