### ISSUE TITLE
What are v2.0.4 and v2.0.5?

### ISSUE THREAD

**Issue by rpearce** [egoist/rollup-plugin-postcss#225]
Two patch publishes have been released in the past 48 hours or so, and I'm curious what they contain, for they are not checked in to version control.

**Comment by SASUKE40** [comment]
@Himself65 
[changelog.md](https://github.com/egoist/changelog.md) could not generate the content for v2.0.4 and v2.0.5 due to the loss colon of commits' message, such as `fix linebreak to lf on all files` [`e118cb10eb72e9f75edac4eae18177eaa3dc1c47`].

@egoist 
[changelog.md](https://github.com/egoist/changelog.md) will generate the wrong link which contains colon in the user's scope, such as [https://github.com/:egoist/rollup-plugin-postcss/releases/tag/v2.0.3](https://github.com/:egoist/rollup-plugin-postcss/releases/tag/v2.0.3). `:egoist` should be `egoist`. I am finding the exact problem.

**Comment by SASUKE40** [comment]
@rpearce 
We are dealing with the CI migration and the changelog will be updated soon.
#221

**Comment by egoist** [comment]
The changelog is now managed by semantic-release using GitHub Releases: https://github.com/egoist/rollup-plugin-postcss/releases
